baseURL = "https://jjunqueira.github.io/goproject-site"
publishDir = "docs"
languageCode = "en-us"
title = "Goproject"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]
    # Souce Code repository section
    description = "Go project consistency made easy"
    github_repository = "https://github.com/jjunqueira/goproject"
    version = "0.0.1"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Getting Started"
    url = "/getting-started"
    weight = 2
